/* FORMULARIO TRATADO COM DESCRICAO */

SELECT
ID_RESPOSTA,
FAIXA_ETÁRIA,
GENERO,
TIPO_DE_MORADIA,
QUANTIDADE_MORADORES,
BAIRRO_RESIDÊNCIA,
REGIAO,
ENDERECO,
TERRENO_BALDIO_PROXIMO,
POSSUI_CONHECIMENTO_SOBRE_DENGUE,
FAMILIARIDADE_SINTOMAS_DENGUE,
CAUSAS_DA_DENGUE,
TIPO_SANGUINEO,
ESTADO_CIVIL,
RENDA_FAMILIAR,
SABE_O_QUE_FAZER_CASO_CONTAMINADO,
CONHECE_ALGUÉM_QUE_TEVE_DENGUE,
CONHECE_DIFERENCAS_MOSQUITO,
SABE_REPELENTE_USAR,
CONTRAIU_DENGUE,
CONHECE_SINTOMAS,
ELIMINAR_FOCO,
VERIFICAÇÕES_DE_IDENTIFICACAO

FROM FORMULARIO_TRATADO FT

INNER JOIN REGIÃO R ON R.CODIGO_REGIAO = FT.CODIGO_REGIAO AND R.CODIGO_BAIRRO = FT.CODIGO_BAIRRO
INNER JOIN FAIXA_ETARIA FE ON FE.CODIGO_FAIXA = FT.CODIGO_FAIXA
INNER JOIN GENERO G ON G.CODIGO_GENERO = FT.CODIGO_GENERO
INNER JOIN MORADIA M ON M.CODIGO_MORADIA = FT.CODIGO_MORADIA
INNER JOIN MORADORES MR ON MR.CODIGO_MORADORES = FT.CODIGO_MORADORES
INNER JOIN ENDERECO E ON E.CODIGO_ENDERECO = FT.CODIGO_ENDERECO
INNER JOIN CAUSAS_DENGUE CD ON CD.CODIGO_CAUSA = FT.CODIGO_CAUSA
INNER JOIN TIPO_SANGUE TS ON TS.CODIGO_TIPO_SANGUINEO = FT.CODIGO_TIPO_SANGUINEO
INNER JOIN ESTADO_CIVIL EC ON EC.CODIGO_ESTADO_CIVIL = FT.CODIGO_ESTADO_CIVIL
INNER JOIN RENDA_FAMILIAR RF ON RF.CODIGO_RENDA_FAMILIAR = FT.CODIGO_RENDA_FAMILIAR
INNER JOIN CONHECE_SINTOMAS CS ON CS.CODIGO_SINTOMAS = FT.CODIGO_SINTOMAS
INNER JOIN ELIMINAR_FOCO EF ON EF.CODIGO_ELIMINAR = FT.CODIGO_ELIMINAR_FOCO

ORDER BY 1 ASC


/*FAIXA ETARIA*/

SELECT
    FE.FAIXA_ETÁRIA,
    COUNT(*) AS QUANTIDADE
FROM FORMULARIO_TRATADO FT

INNER JOIN FAIXA_ETARIA FE ON FE.CODIGO_FAIXA = FT.CODIGO_FAIXA

GROUP BY FE.FAIXA_ETÁRIA
ORDER BY FE.FAIXA_ETÁRIA ASC;

/*GENERO*/

SELECT
    G.GENERO,
    COUNT(*) AS QUANTIDADE,
    ROUND(COUNT(*) * 100.0 / (SELECT COUNT(*) FROM FORMULARIO_TRATADO), 2) AS PORCENTAGEM
FROM FORMULARIO_TRATADO FT
INNER JOIN GENERO G ON G.CODIGO_GENERO = FT.CODIGO_GENERO
GROUP BY G.GENERO
ORDER BY G.GENERO ASC;


/*Quantidade por bairro*/

SELECT
    R.BAIRRO_RESIDÊNCIA,
    COUNT(*) AS QUANTIDADE
    
FROM FORMULARIO_TRATADO FT

INNER JOIN REGIÃO R ON R.CODIGO_REGIAO = FT.CODIGO_REGIAO AND R.CODIGO_BAIRRO = FT.CODIGO_BAIRRO


WHERE CONTRAIU_DENGUE = 'SIM'

GROUP BY R.BAIRRO_RESIDÊNCIA
ORDER BY QUANTIDADE DESC, R.BAIRRO_RESIDÊNCIA ASC;

/*Quantidade de pessoas que já pegaram dengue*/

SELECT
    FT.CONTRAIU_DENGUE AS CONTRAIU_DENGUE,
    COUNT(*) AS QUANTIDADE,
    ROUND(COUNT(*) * 100.0 / (SELECT COUNT(*) FROM FORMULARIO_TRATADO WHERE CONTRAIU_DENGUE IS NOT NULL), 2) AS PORCENTAGEM
FROM FORMULARIO_TRATADO FT
WHERE FT.CONTRAIU_DENGUE IS NOT NULL
GROUP BY FT.CONTRAIU_DENGUE
ORDER BY CONTRAIU_DENGUE ASC;

/*Terreno baldio proximo da casa / apartamento por contagem de dengue*/

SELECT
    M.TIPO_DE_MORADIA,
    FT.TERRENO_BALDIO_PROXIMO,
    COUNT(CASE WHEN FT.CONTRAIU_DENGUE = 'Sim' THEN 1 END) AS PESSOAS_PEGARAM_DENGUE
FROM FORMULARIO_TRATADO FT
INNER JOIN MORADIA M ON M.CODIGO_MORADIA = FT.CODIGO_MORADIA
WHERE FT.TERRENO_BALDIO_PROXIMO IS NOT NULL
GROUP BY M.TIPO_DE_MORADIA, FT.TERRENO_BALDIO_PROXIMO;


